Repository spon-us/SponUs-BE, pull requests merged in 2024-06, with the labels that each got.

#313 feat: 검색어 개별 삭제 기능 구현
  api/src/main/java/com/sponus/sponusbe/domain/organization/controller/OrganizationController.java
  api/src/main/java/com/sponus/sponusbe/domain/organization/service/OrganizationService.java
Labels: feat

#315 fix: ci 이슈 템플릿 수정
  .github/ISSUE_TEMPLATE/ci.md
Labels: fix

#317 ci: 배포 방식 변경
  .ebextensions-dev/00-set-timezone.config
  .github/workflows/cd_gradle.yml
  .platform/nginx.conf
  Dockerfile
  Dockerrun.aws.json
  supervisord.conf
Labels: ci

#319 fix: 헬스체크 api 생성
  api/src/main/java/com/sponus/sponusbe/auth/controller/HealthCheck.java
Labels: fix, ci

#321 fix: 헬스체크 api 권한 설정
  core/core-infra-security/src/main/java/com/sponus/coreinfrasecurity/config/SecurityConfig.java
Labels: fix, ci

#323 ️refactor: 검색 api, 검색어 저장 api 분리
  api/src/main/java/com/sponus/sponusbe/domain/organization/controller/OrganizationController.java
  api/src/main/java/com/sponus/sponusbe/domain/organization/dto/OrganizationSearchRequest.java
  api/src/main/java/com/sponus/sponusbe/domain/organization/service/OrganizationService.java
Labels: feat, refactor

#329 fix: LogoutFilter 위치 수정 및 handler 정의
  core/core-infra-security/src/main/java/com/sponus/coreinfrasecurity/config/SecurityConfig.java
Labels: fix, refactor

#333 feat: Organization 에 Club & Company 별 Type 함께 반환
  api/src/main/java/com/sponus/sponusbe/domain/organization/club/dto/ClubUpdateRequest.java
  api/src/main/java/com/sponus/sponusbe/domain/organization/company/dto/CompanyUpdateRequest.java
  api/src/main/java/com/sponus/sponusbe/domain/organization/company/dto/OrganizationGetResponse.java
  api/src/main/java/com/sponus/sponusbe/domain/organization/controller/OrganizationController.java
  api/src/main/java/com/sponus/sponusbe/domain/organization/dto/OrganizationCreateRequest.java
  api/src/main/java/com/sponus/sponusbe/domain/organization/dto/request/OrganizationCreateRequest.java
  api/src/main/java/com/sponus/sponusbe/domain/organization/dto/request/OrganizationSearchRequest.java
  api/src/main/java/com/sponus/sponusbe/domain/organization/dto/request/PageCondition.java
  api/src/main/java/com/sponus/sponusbe/domain/organization/dto/response/OrganizationImageUploadResponse.java
  api/src/main/java/com/sponus/sponusbe/domain/organization/dto/response/OrganizationSearchResponse.java
  api/src/main/java/com/sponus/sponusbe/domain/organization/dto/response/PageResponse.java
  api/src/main/java/com/sponus/sponusbe/domain/organization/service/OrganizationService.java
  api/src/test/java/com/sponus/sponusbe/domain/organization/SecurityAuthTest.java
  core/core-domain/src/main/java/com/sponus/coredomain/domain/organization/Club.java
  core/core-domain/src/main/java/com/sponus/coredomain/domain/organization/Company.java
  core/core-domain/src/main/java/com/sponus/coredomain/domain/organization/Organization.java
  core/core-domain/src/main/java/com/sponus/coredomain/domain/organization/enums/CompanyType.java
Labels: feat
