Repository spon-us/SponUs-BE, pull requests merged in 2024-02, with the labels that each got.

#89 ✨ feat: 태그 생성 기능 개발
  http/test.http
  src/main/java/com/sponus/sponusbe/domain/organization/dto/OrganizationDetailGetResponse.java
  src/main/java/com/sponus/sponusbe/domain/organization/dto/TagGetResponse.java
  src/main/java/com/sponus/sponusbe/domain/organization/entity/Organization.java
  src/main/java/com/sponus/sponusbe/domain/organization/entity/OrganizationTag.java
  src/main/java/com/sponus/sponusbe/domain/tag/controller/TagController.java
  src/main/java/com/sponus/sponusbe/domain/tag/dto/TagGetResponse.java
  src/main/java/com/sponus/sponusbe/domain/tag/dto/request/TagCreateRequest.java
  src/main/java/com/sponus/sponusbe/domain/tag/dto/resposne/TagCreateResponse.java
  src/main/java/com/sponus/sponusbe/domain/tag/entity/Tag.java
  src/main/java/com/sponus/sponusbe/domain/tag/exception/TagErrorCode.java
  src/main/java/com/sponus/sponusbe/domain/tag/exception/TagException.java
  src/main/java/com/sponus/sponusbe/domain/tag/repository/TagRepository.java
  src/main/java/com/sponus/sponusbe/domain/tag/service/TagQueryService.java
  src/main/java/com/sponus/sponusbe/domain/tag/service/TagService.java
Labels: feat

#90 :sparkles: feat: 북마크 등록 및 취소 기능 개발
  http/test.http
  src/main/java/com/sponus/sponusbe/domain/bookmark/controller/BookmarkController.java
  src/main/java/com/sponus/sponusbe/domain/bookmark/dto/BookmarkToggleRequest.java
  src/main/java/com/sponus/sponusbe/domain/bookmark/dto/BookmarkToggleResponse.java
  src/main/java/com/sponus/sponusbe/domain/bookmark/entity/Bookmark.java
  src/main/java/com/sponus/sponusbe/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/com/sponus/sponusbe/domain/bookmark/service/BookmarkService.java
Labels: feat

#87 ✨ feat: ️이메일 인증 구현
  build.gradle
  http/test.http
  src/main/java/com/sponus/sponusbe/domain/organization/controller/OrganizationController.java
  src/main/java/com/sponus/sponusbe/domain/organization/service/OrganizationService.java
  src/main/java/com/sponus/sponusbe/global/config/EmailConfig.java
Labels: feat

#101 ✨ feat: 북마크 최근 저장순 조회 기능 개발
  http/test.http
  src/main/java/com/sponus/sponusbe/domain/bookmark/controller/BookmarkController.java
  src/main/java/com/sponus/sponusbe/domain/bookmark/dto/BookmarkGetResponse.java
  src/main/java/com/sponus/sponusbe/domain/bookmark/entity/Bookmark.java
  src/main/java/com/sponus/sponusbe/domain/bookmark/entity/BookmarkStatus.java
  src/main/java/com/sponus/sponusbe/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/com/sponus/sponusbe/domain/bookmark/service/BookmarkService.java
Labels: feat

#93 ✨ feat: 태그 조회 기능 개발
  http/test.http
  src/main/java/com/sponus/sponusbe/domain/tag/controller/TagController.java
  src/main/java/com/sponus/sponusbe/domain/tag/service/TagQueryService.java
  src/main/resources/data.sql
Labels: feat

#94 ✨ feat: 태그 수정 기능 개발
  http/test.http
  src/main/java/com/sponus/sponusbe/domain/tag/controller/TagController.java
  src/main/java/com/sponus/sponusbe/domain/tag/dto/request/TagUpdateRequest.java
  src/main/java/com/sponus/sponusbe/domain/tag/entity/Tag.java
  src/main/java/com/sponus/sponusbe/domain/tag/service/TagService.java
Labels: feat

#95 ✨ feat: 태그 삭제 기능 개발
  http/test.http
  src/main/java/com/sponus/sponusbe/domain/tag/controller/TagController.java
  src/main/java/com/sponus/sponusbe/domain/tag/service/TagService.java
Labels: feat

#100 ✨ feat: 조직 링크 생성 기능 개발
  http/test.http
  src/main/java/com/sponus/sponusbe/domain/organization/dto/OrganizationDetailGetResponse.java
  src/main/java/com/sponus/sponusbe/domain/organization/entity/Organization.java
  src/main/java/com/sponus/sponusbe/domain/organizationLink/controller/OrganizationLinkController.java
  src/main/java/com/sponus/sponusbe/domain/organizationLink/dto/request/OrganizationLinkCreateRequest.java
  src/main/java/com/sponus/sponusbe/domain/organizationLink/dto/response/OrganizationLinkCreateResponse.java
  src/main/java/com/sponus/sponusbe/domain/organizationLink/dto/response/OrganizationLinkGetResponse.java
  src/main/java/com/sponus/sponusbe/domain/organizationLink/entity/OrganizationLink.java
  src/main/java/com/sponus/sponusbe/domain/organizationLink/exception/OrganizationLinkErrorCode.java
  src/main/java/com/sponus/sponusbe/domain/organizationLink/exception/OrganizationLinkException.java
  src/main/java/com/sponus/sponusbe/domain/organizationLink/repository/OrganizationLinkRepository.java
  src/main/java/com/sponus/sponusbe/domain/organizationLink/service/OrganizationLinkQueryService.java
  src/main/java/com/sponus/sponusbe/domain/organizationLink/service/OrganizationLinkService.java
  src/main/java/com/sponus/sponusbe/domain/tag/exception/TagErrorCode.java
Labels: feat

#106 🐛 fix: propose 오류 수정
  src/main/java/com/sponus/sponusbe/domain/propose/controller/ProposeController.java
  src/main/java/com/sponus/sponusbe/domain/propose/dto/request/ProposeCreateRequest.java
  src/main/java/com/sponus/sponusbe/domain/propose/dto/request/ProposeGetCondition.java
  src/main/java/com/sponus/sponusbe/domain/propose/dto/request/ProposeSearchType.java
  src/main/java/com/sponus/sponusbe/domain/propose/entity/Propose.java
  src/main/java/com/sponus/sponusbe/domain/propose/service/ProposeService.java
Labels: fix

#113 ✨ feat: 조직 링크 조회 기능 개발
  http/test.http
  src/main/java/com/sponus/sponusbe/domain/organizationLink/controller/OrganizationLinkController.java
  src/main/java/com/sponus/sponusbe/domain/organizationLink/exception/OrganizationLinkErrorCode.java
  src/main/java/com/sponus/sponusbe/domain/organizationLink/service/OrganizationLinkQueryService.java
Labels: feat

#114 ✨ feat: 조직 링크 수정 기능 개발
  http/test.http
  src/main/java/com/sponus/sponusbe/domain/organizationLink/controller/OrganizationLinkController.java
  src/main/java/com/sponus/sponusbe/domain/organizationLink/dto/request/OrganizationLinkUpdateRequest.java
  src/main/java/com/sponus/sponusbe/domain/organizationLink/entity/OrganizationLink.java
  src/main/java/com/sponus/sponusbe/domain/organizationLink/service/OrganizationLinkService.java
Labels: feat

#121 ✨ feat: 제안 조회시 첨부파일 추가, 공고 상태 변경
  src/main/java/com/sponus/sponusbe/domain/announcement/dto/request/AnnouncementCreateRequest.java
  src/main/java/com/sponus/sponusbe/domain/announcement/dto/request/AnnouncementUpdateRequest.java
  src/main/java/com/sponus/sponusbe/domain/announcement/entity/Announcement.java
  src/main/java/com/sponus/sponusbe/domain/announcement/entity/enums/AnnouncementStatus.java
  src/main/java/com/sponus/sponusbe/domain/announcement/exception/AnnouncementErrorCode.java
  src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementService.java
  src/main/java/com/sponus/sponusbe/domain/propose/controller/ProposeController.java
  src/main/java/com/sponus/sponusbe/domain/propose/dto/response/ProposeDetailGetResponse.java
  src/main/java/com/sponus/sponusbe/domain/propose/dto/response/ProposeSummaryGetResponse.java
  src/main/java/com/sponus/sponusbe/domain/propose/entity/Propose.java
  src/main/java/com/sponus/sponusbe/domain/propose/entity/ProposeAttachment.java
  src/main/java/com/sponus/sponusbe/domain/propose/entity/ProposeImage.java
  src/main/java/com/sponus/sponusbe/domain/propose/repository/ProposeAttachmentRepository.java
  src/main/java/com/sponus/sponusbe/domain/propose/repository/ProposeImageRepository.java
  src/main/java/com/sponus/sponusbe/domain/propose/service/ProposeQueryService.java
  src/main/java/com/sponus/sponusbe/domain/propose/service/ProposeService.java
  src/main/java/com/sponus/sponusbe/global/util/MultipartJackson2HttpMessageConverter.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: feat

#123 ✨ feat: 북마크된 공고 목록 저장 많은 순 조회 기능 개발
  http/test.http
  src/main/java/com/sponus/sponusbe/domain/bookmark/controller/BookmarkController.java
  src/main/java/com/sponus/sponusbe/domain/bookmark/dto/BookmarkGetResponse.java
  src/main/java/com/sponus/sponusbe/domain/bookmark/entity/Bookmark.java
  src/main/java/com/sponus/sponusbe/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/com/sponus/sponusbe/domain/bookmark/service/BookmarkService.java
Labels: feat

#126 ♻️ refactor: fcm토큰 로그인/로그아웃 추가
  http/test.http
  src/main/java/com/sponus/sponusbe/auth/jwt/filter/CustomLoginFilter.java
  src/main/java/com/sponus/sponusbe/auth/jwt/filter/CustomLogoutHandler.java
  src/main/java/com/sponus/sponusbe/global/config/SecurityConfig.java
Labels: refactor

#128 ✨ feat: 공고 기능 이미지 추가
  http/test.http
  src/main/java/com/sponus/sponusbe/domain/announcement/controller/AnnouncementController.java
  src/main/java/com/sponus/sponusbe/domain/announcement/dto/request/AnnouncementCreateRequest.java
  src/main/java/com/sponus/sponusbe/domain/announcement/dto/response/AnnouncementBriefResponse.java
  src/main/java/com/sponus/sponusbe/domain/announcement/dto/response/AnnouncementDetailResponse.java
  src/main/java/com/sponus/sponusbe/domain/announcement/dto/response/AnnouncementImageResponse.java
  src/main/java/com/sponus/sponusbe/domain/announcement/dto/response/AnnouncementSummaryResponse.java
  src/main/java/com/sponus/sponusbe/domain/announcement/entity/Announcement.java
  src/main/java/com/sponus/sponusbe/domain/announcement/entity/AnnouncementImage.java
  src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementQueryService.java
  src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementService.java
  src/main/resources/data.sql
Labels: feat

#136 :sparkles: feat: 보고서 작성 기능 첨부파일 추가
  src/main/java/com/sponus/sponusbe/domain/report/controller/ReportController.java
  src/main/java/com/sponus/sponusbe/domain/report/dto/ReportAttachmentResponse.java
  src/main/java/com/sponus/sponusbe/domain/report/entity/Report.java
  src/main/java/com/sponus/sponusbe/domain/report/entity/ReportAttachment.java
  src/main/java/com/sponus/sponusbe/domain/report/service/ReportService.java
Labels: feat

#132 ️♻️ refactor: 이메일 인증 시큐리티 권한 추가 및 알림 테스트 api 권한 삭제
  http/test.http
  out/production/resources/data.sql
  src/main/java/com/sponus/sponusbe/global/config/SecurityConfig.java
Labels: fix, refactor

#138 ✨ feat: 보고서 조회 기능 이미지, 첨부파일 추가
  src/main/java/com/sponus/sponusbe/domain/report/controller/ReportController.java
  src/main/java/com/sponus/sponusbe/domain/report/dto/ReportCreateRequest.java
  src/main/java/com/sponus/sponusbe/domain/report/dto/ReportGetResponse.java
  src/main/java/com/sponus/sponusbe/domain/report/entity/Report.java
  src/main/java/com/sponus/sponusbe/domain/report/service/ReportQueryService.java
  src/main/java/com/sponus/sponusbe/domain/report/service/ReportService.java
Labels: feat

#146 :recycle: refactor: 북마크 cascade 처리
  src/main/java/com/sponus/sponusbe/domain/bookmark/entity/Bookmark.java
Labels: feat

#144 ✨ feat: 공고 카테고리별 조회
  http/test.http
  out/production/resources/data.sql
  src/main/java/com/sponus/sponusbe/domain/announcement/controller/AnnouncementController.java
  src/main/java/com/sponus/sponusbe/domain/announcement/repository/AnnouncementRepository.java
  src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementQueryService.java
  src/main/resources/data.sql
Labels: feat

#149 ♻️ refactor : request dto 및 엔티티에 null 허용
  http/test.http
  src/main/java/com/sponus/sponusbe/domain/organization/dto/OrganizationJoinRequest.java
  src/main/java/com/sponus/sponusbe/domain/organization/entity/Organization.java
Labels: refactor

#154 ✨ feat: 북마크 조회 기능 이미지 추가
  src/main/java/com/sponus/sponusbe/domain/announcement/entity/Announcement.java
  src/main/java/com/sponus/sponusbe/domain/bookmark/controller/BookmarkController.java
  src/main/java/com/sponus/sponusbe/domain/bookmark/dto/BookmarkGetResponse.java
  src/main/java/com/sponus/sponusbe/domain/bookmark/entity/Bookmark.java
  src/main/java/com/sponus/sponusbe/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/com/sponus/sponusbe/domain/bookmark/service/BookmarkService.java
Labels: feat

#155 🐛 fix: 공고, 제안 관련 이미지 API 수정
  src/main/java/com/sponus/sponusbe/domain/announcement/controller/AnnouncementController.java
  src/main/java/com/sponus/sponusbe/domain/announcement/dto/request/AnnouncementCreateRequest.java
  src/main/java/com/sponus/sponusbe/domain/announcement/dto/response/AnnouncementSummaryResponse.java
  src/main/java/com/sponus/sponusbe/domain/announcement/entity/Announcement.java
  src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementService.java
  src/main/java/com/sponus/sponusbe/domain/propose/controller/ProposeController.java
  src/main/java/com/sponus/sponusbe/domain/propose/dto/request/ProposeGetCondition.java
  src/main/java/com/sponus/sponusbe/domain/propose/dto/request/ProposeSearchType.java
  src/main/java/com/sponus/sponusbe/domain/propose/dto/response/ProposeAttachmentResponse.java
  src/main/java/com/sponus/sponusbe/domain/propose/dto/response/ProposeDetailGetResponse.java
  src/main/java/com/sponus/sponusbe/domain/propose/dto/response/ProposeSummaryGetResponse.java
  src/main/java/com/sponus/sponusbe/domain/propose/entity/Propose.java
  src/main/java/com/sponus/sponusbe/domain/propose/entity/ProposeImage.java
  src/main/java/com/sponus/sponusbe/domain/propose/service/ProposeQueryService.java
  src/main/java/com/sponus/sponusbe/domain/propose/service/ProposeService.java
Labels: fix, feat

#152 ✨ feat: 최근 조회한 공고 기능 구현
  src/main/java/com/sponus/sponusbe/auth/jwt/filter/CustomLoginFilter.java
  src/main/java/com/sponus/sponusbe/auth/jwt/filter/CustomLogoutHandler.java
  src/main/java/com/sponus/sponusbe/auth/jwt/util/JwtUtil.java
  src/main/java/com/sponus/sponusbe/auth/jwt/util/RedisUtil.java
  src/main/java/com/sponus/sponusbe/domain/announcement/controller/AnnouncementController.java
  src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementQueryService.java
  src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementService.java
  src/main/java/com/sponus/sponusbe/domain/bookmark/entity/Bookmark.java
  src/main/java/com/sponus/sponusbe/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/com/sponus/sponusbe/domain/bookmark/service/BookmarkService.java
  src/main/java/com/sponus/sponusbe/domain/organizationLink/controller/OrganizationLinkController.java
  src/main/java/com/sponus/sponusbe/domain/organizationLink/dto/request/OrganizationLinkUpdateRequest.java
  src/main/java/com/sponus/sponusbe/domain/organizationLink/entity/OrganizationLink.java
  src/main/java/com/sponus/sponusbe/domain/organizationLink/service/OrganizationLinkQueryService.java
  src/main/java/com/sponus/sponusbe/domain/report/controller/ReportController.java
  src/main/java/com/sponus/sponusbe/domain/report/service/ReportService.java
  src/main/java/com/sponus/sponusbe/domain/tag/controller/TagController.java
Labels: feat

#164 ✨ feat: 제안 열람됨 상태 추가 & 제안 수락 기능 분리
  http/test.http
  src/main/java/com/sponus/sponusbe/domain/propose/controller/ProposeController.java
  src/main/java/com/sponus/sponusbe/domain/propose/dto/request/ProposeStatusUpdateRequest.java
  src/main/java/com/sponus/sponusbe/domain/propose/dto/request/ProposeUpdateRequest.java
  src/main/java/com/sponus/sponusbe/domain/propose/entity/Propose.java
  src/main/java/com/sponus/sponusbe/domain/propose/entity/ProposeStatus.java
  src/main/java/com/sponus/sponusbe/domain/propose/exception/ProposeErrorCode.java
  src/main/java/com/sponus/sponusbe/domain/propose/service/ProposeQueryService.java
  src/main/java/com/sponus/sponusbe/domain/propose/service/ProposeService.java
Labels: feat

#166 ✨feat: 알림 삭제 구현 및 임시 fcm 토큰 발급
  http/test.http
  src/main/java/com/sponus/sponusbe/domain/notification/exception/NotificationErrorCode.java
  src/main/java/com/sponus/sponusbe/domain/notification/exception/NotificationException.java
  src/main/java/com/sponus/sponusbe/domain/notification/service/FirebaseService.java
  src/main/java/com/sponus/sponusbe/domain/organization/controller/OrganizationController.java
  src/main/java/com/sponus/sponusbe/domain/organization/service/OrganizationService.java
Labels: feat

#168 :recycle: refactor: 제안 보내기 알림 추가
  src/main/java/com/sponus/sponusbe/domain/notification/entity/Notification.java
  src/main/java/com/sponus/sponusbe/domain/propose/controller/ProposeController.java
  src/main/java/com/sponus/sponusbe/domain/propose/service/ProposeService.java
Labels: refactor

#171 ✨ feat: 알림 읽음 로직 추가 & 공고 카테고리 추가
  out/production/resources/application.yml
  src/main/java/com/sponus/sponusbe/domain/announcement/entity/enums/AnnouncementCategory.java
  src/main/java/com/sponus/sponusbe/domain/notification/entity/Notification.java
  src/main/java/com/sponus/sponusbe/domain/organization/controller/OrganizationController.java
  src/main/java/com/sponus/sponusbe/domain/organization/service/OrganizationService.java
  src/main/java/com/sponus/sponusbe/domain/s3/S3Service.java
  src/main/resources/application.yml
Labels: feat

#177 :recycle: refactor: 공고 카테고리별 조회 최근순으로 변경
  out/production/resources/data.sql
  src/main/java/com/sponus/sponusbe/domain/announcement/dto/response/AnnouncementSummaryResponse.java
  src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementQueryService.java
  src/main/resources/data.sql
Labels: refactor

#182 ️♻️ refactor: 공고 상태 변경 기능 분리
  src/main/java/com/sponus/sponusbe/domain/announcement/controller/AnnouncementController.java
  src/main/java/com/sponus/sponusbe/domain/announcement/dto/request/AnnouncementUpdateRequest.java
  src/main/java/com/sponus/sponusbe/domain/announcement/dto/response/AnnouncementStatusUpdateResponse.java
  src/main/java/com/sponus/sponusbe/domain/announcement/entity/Announcement.java
  src/main/java/com/sponus/sponusbe/domain/announcement/entity/enums/AnnouncementStatus.java
  src/main/java/com/sponus/sponusbe/domain/announcement/exception/AnnouncementErrorCode.java
  src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementService.java
  src/main/java/com/sponus/sponusbe/domain/propose/controller/ProposeController.java
  src/main/java/com/sponus/sponusbe/domain/propose/dto/request/ProposeStatusUpdateRequest.java
  src/main/java/com/sponus/sponusbe/domain/propose/entity/ProposeStatus.java
  src/main/java/com/sponus/sponusbe/domain/propose/exception/ProposeErrorCode.java
  src/main/java/com/sponus/sponusbe/domain/propose/service/ProposeService.java
  src/main/java/com/sponus/sponusbe/global/common/exception/GlobalExceptionHandler.java
Labels: refactor

#183 ✨ feat: 북마크된 공고 목록 조회 많은 순 조회 기능 개발
  src/main/java/com/sponus/sponusbe/domain/bookmark/controller/BookmarkController.java
  src/main/java/com/sponus/sponusbe/domain/bookmark/dto/BookmarkGetResponse.java
  src/main/java/com/sponus/sponusbe/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/com/sponus/sponusbe/domain/bookmark/service/BookmarkQueryService.java
  src/main/java/com/sponus/sponusbe/domain/bookmark/service/BookmarkService.java
  src/main/java/com/sponus/sponusbe/domain/report/service/ReportService.java
Labels: feat

#186 ♻️ refactor: 공고 조회, 공고 카테고리 조회 수정
  src/main/java/com/sponus/sponusbe/domain/announcement/dto/response/AnnouncementDetailResponse.java
  src/main/java/com/sponus/sponusbe/domain/announcement/repository/AnnouncementRepository.java
  src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementQueryService.java
Labels: refactor

#188 :sparkles: feat: 게시중 상태 내가 올린 공고 목록 조회 개발
  src/main/java/com/sponus/sponusbe/domain/announcement/controller/AnnouncementController.java
  src/main/java/com/sponus/sponusbe/domain/announcement/repository/AnnouncementRepository.java
  src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementQueryService.java
  src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementService.java
  src/main/java/com/sponus/sponusbe/domain/bookmark/service/BookmarkQueryService.java
Labels: feat

#191 :sparkles: feat: 내가 올린 공고 목록 조회 기능 개발
  src/main/java/com/sponus/sponusbe/domain/announcement/controller/AnnouncementController.java
  src/main/java/com/sponus/sponusbe/domain/announcement/repository/AnnouncementRepository.java
  src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementQueryService.java
Labels: feat

#193 :recycle: refactor: 공고 조회 기능 Service 수정
  src/main/java/com/sponus/sponusbe/domain/announcement/repository/AnnouncementRepository.java
  src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementQueryService.java
Labels: refactor

#197 🐛 fix: firebase 요청 헤더 변경
  http/test.http
  src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementService.java
  src/main/java/com/sponus/sponusbe/domain/notification/service/FirebaseService.java
Labels: fix

#199 :bug: fix: 알림 에러 해결
  .github/workflows/ci_gradle.yml
  src/main/java/com/sponus/sponusbe/domain/notification/service/FirebaseService.java
Labels: fix

#201 ️♻️ refactor: response 북마크 횟수 추가
  src/main/java/com/sponus/sponusbe/domain/announcement/dto/response/AnnouncementSummaryResponse.java
  src/main/java/com/sponus/sponusbe/domain/announcement/entity/Announcement.java
Labels: refactor

#203 ✨ feat: 제안에 보고서 작성상태 추가
  src/main/java/com/sponus/sponusbe/domain/propose/controller/ProposeController.java
  src/main/java/com/sponus/sponusbe/domain/propose/dto/response/DateGroupedProposeResponse.java
  src/main/java/com/sponus/sponusbe/domain/propose/dto/response/ProposeSummaryGetResponse.java
  src/main/java/com/sponus/sponusbe/domain/propose/entity/Propose.java
  src/main/java/com/sponus/sponusbe/domain/propose/service/ProposeQueryService.java
Labels: feat

#204 ✨ feat: 임시 결제 승인 기능 구현
  build.gradle
  src/main/java/com/sponus/sponusbe/domain/payment/controller/PaymentController.java
  src/main/java/com/sponus/sponusbe/domain/payment/controller/PaymentViewController.java
  src/main/java/com/sponus/sponusbe/domain/payment/dto/PaymentRequest.java
  src/main/java/com/sponus/sponusbe/global/config/SecurityConfig.java
  src/main/resources/templates/payment.html
Labels: feat

#208 ✨ feat: 제안 결제 성공 시 상태 변경
  src/main/java/com/sponus/sponusbe/domain/payment/controller/PaymentController.java
  src/main/java/com/sponus/sponusbe/domain/payment/dto/PaymentRequest.java
  src/main/java/com/sponus/sponusbe/domain/payment/service/PaymentService.java
  src/main/java/com/sponus/sponusbe/domain/propose/entity/Propose.java
  src/main/java/com/sponus/sponusbe/domain/propose/entity/ProposeStatus.java
  src/main/java/com/sponus/sponusbe/domain/propose/exception/ProposeErrorCode.java
  src/main/java/com/sponus/sponusbe/domain/propose/repository/ProposeRepository.java
  src/main/resources/templates/payment.html
Labels: feat

#212 ♻️ refactor: 토큰 만료 시 응답 개선
  src/main/java/com/sponus/sponusbe/auth/jwt/filter/JwtAuthenticationFilter.java
Labels: refactor

#195 ✨ feat: 조직 이미지 S3 저장 로직 추가
  src/main/java/com/sponus/sponusbe/domain/organization/controller/OrganizationController.java
  src/main/java/com/sponus/sponusbe/domain/organization/dto/OrganizationJoinRequest.java
  src/main/java/com/sponus/sponusbe/domain/organization/dto/OrganizationUpdateRequest.java
  src/main/java/com/sponus/sponusbe/domain/organization/entity/Organization.java
  src/main/java/com/sponus/sponusbe/domain/organization/service/OrganizationService.java
Labels: feat

#216 ♻️ refactor: proposingOrganizationImageUrl 추가
  src/main/java/com/sponus/sponusbe/domain/propose/dto/response/ProposeSummaryGetResponse.java
Labels: refactor

#218 🐛 fix: 공고 및 제안 삭제 문제 해결
  src/main/java/com/sponus/sponusbe/domain/announcement/entity/Announcement.java
Labels: fix

#220 ♻️ refactor: 공고 조회 시 지원 가능 여부 확인
  src/main/java/com/sponus/sponusbe/domain/announcement/dto/response/AnnouncementDetailResponse.java
  src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementService.java
  src/main/java/com/sponus/sponusbe/domain/propose/dto/response/ProposeDetailGetResponse.java
  src/main/java/com/sponus/sponusbe/domain/propose/repository/ProposeRepository.java
Labels: refactor

#222 ✨ feat: 제안 완료(협업 완료) 기능 추가
  src/main/java/com/sponus/sponusbe/domain/propose/entity/ProposeStatus.java
Labels: feat

#240 ♻️ refactor: 알림 조회 최신순으로 수정
  src/main/java/com/sponus/sponusbe/domain/notification/dto/response/NotificationSummaryResponse.java
  src/main/java/com/sponus/sponusbe/domain/notification/entity/Notification.java
  src/main/java/com/sponus/sponusbe/domain/notification/repository/NotificationRepository.java
  src/main/java/com/sponus/sponusbe/domain/organization/service/OrganizationQueryService.java
Labels: refactor

#242 🐛 fix: subOrganizationType null 처리
  src/main/java/com/sponus/sponusbe/domain/organization/dto/OrganizationDetailGetResponse.java
Labels: fix
