Repository spon-us/SponUs-BE, pull requests merged in 2024-05, with the labels that each got.

#278 feat: 포트폴리오 CRUD (+포트폴리오이미지 업로드)
  api/src/main/java/com/sponus/sponusbe/domain/portfolio/controller/PortfolioController.java
  api/src/main/java/com/sponus/sponusbe/domain/portfolio/dto/PortfolioCreateRequest.java
  api/src/main/java/com/sponus/sponusbe/domain/portfolio/dto/PortfolioCreateResponse.java
  api/src/main/java/com/sponus/sponusbe/domain/portfolio/dto/PortfolioDeleteResponse.java
  api/src/main/java/com/sponus/sponusbe/domain/portfolio/dto/PortfolioGetResponse.java
  api/src/main/java/com/sponus/sponusbe/domain/portfolio/dto/PortfolioImageCreateResponse.java
  api/src/main/java/com/sponus/sponusbe/domain/portfolio/dto/PortfolioImageGetResponse.java
  api/src/main/java/com/sponus/sponusbe/domain/portfolio/dto/PortfolioUpdateRequest.java
  api/src/main/java/com/sponus/sponusbe/domain/portfolio/exception/PortfolioErrorCode.java
  api/src/main/java/com/sponus/sponusbe/domain/portfolio/exception/PortfolioException.java
  api/src/main/java/com/sponus/sponusbe/domain/portfolio/service/PortfolioService.java
  core/core-domain/src/main/java/com/sponus/coredomain/domain/portfolio/Portfolio.java
  core/core-domain/src/main/java/com/sponus/coredomain/domain/portfolio/PortfolioImage.java
  core/core-domain/src/main/java/com/sponus/coredomain/domain/portfolio/repository/PortfolioImageRepository.java
  core/core-domain/src/main/java/com/sponus/coredomain/domain/portfolio/repository/PortfolioRepository.java
Labels: feat

#281 feat: 조직 검색, 최근 검색어 기능 구현
  api/src/main/java/com/sponus/sponusbe/domain/organization/company/dto/CompanyGetResponse.java
  api/src/main/java/com/sponus/sponusbe/domain/organization/company/dto/OrganizationGetResponse.java
  api/src/main/java/com/sponus/sponusbe/domain/organization/controller/OrganizationController.java
  api/src/main/java/com/sponus/sponusbe/domain/organization/controller/PageResponse.java
  api/src/main/java/com/sponus/sponusbe/domain/organization/dto/OrganizationSearchResponse.java
  api/src/main/java/com/sponus/sponusbe/domain/organization/service/OrganizationService.java
  core/core-domain/src/main/java/com/sponus/coredomain/domain/organization/Club.java
  core/core-domain/src/main/java/com/sponus/coredomain/domain/organization/repository/OrganizationRepository.java
  core/core-infra-redis/src/main/java/com/sponus/coreinfraredis/entity/SearchHistory.java
  core/core-infra-redis/src/main/java/com/sponus/coreinfraredis/repository/SearchHistoryRepository.java
  core/core-infra-security/src/main/java/com/sponus/coreinfrasecurity/config/SecurityConfig.java
Labels: feat, refactor

#283 refactor: login 리팩토링
  api/src/main/java/com/sponus/sponusbe/auth/controller/AuthController.java
  api/src/main/java/com/sponus/sponusbe/domain/bookmark/controller/BookmarkController.java
  api/src/main/java/com/sponus/sponusbe/domain/notification/controller/FirebaseTestController.java
  api/src/main/java/com/sponus/sponusbe/domain/organization/club/controller/ClubController.java
  api/src/main/java/com/sponus/sponusbe/domain/organization/company/controller/CompanyController.java
  api/src/main/java/com/sponus/sponusbe/domain/organization/controller/OrganizationController.java
  api/src/main/java/com/sponus/sponusbe/domain/organizationLink/controller/OrganizationLinkController.java
  api/src/main/java/com/sponus/sponusbe/domain/portfolio/controller/PortfolioController.java
  api/src/main/java/com/sponus/sponusbe/domain/propose/controller/ProposeController.java
  api/src/main/java/com/sponus/sponusbe/domain/s3/S3TestController.java
  api/src/main/java/com/sponus/sponusbe/global/enums/ApiPath.java
  core/core-infra-security/src/main/java/com/sponus/coreinfrasecurity/config/SecurityConfig.java
Labels: refactor

#285 refactor: update api ver 1 -> 2
  http/test.http
Labels: refactor

#287 feat: impl duplicate email verification
  api/src/main/java/com/sponus/sponusbe/auth/controller/AuthController.java
  core/core-domain/src/main/java/com/sponus/coredomain/domain/organization/repository/OrganizationRepository.java
  core/core-infra-security/src/main/java/com/sponus/coreinfrasecurity/config/SecurityConfig.java
Labels: feat, refactor

#290 feat: Impl sending authentication code with email
  api/src/main/java/com/sponus/sponusbe/auth/controller/AuthController.java
  core/core-domain/src/main/java/com/sponus/coredomain/domain/organization/repository/OrganizationRepository.java
  core/core-infra-email/build.gradle
  core/core-infra-email/src/main/java/com/sponus/coreinfraemail/EmailUtil.java
  core/core-infra-security/src/main/java/com/sponus/coreinfrasecurity/config/SecurityConfig.java
Labels: feat

#292 feat: Impl code verification api
  api/src/main/java/com/sponus/sponusbe/auth/controller/AuthController.java
  core/core-infra-email/src/main/java/com/sponus/coreinfraemail/EmailUtil.java
  core/core-infra-security/src/main/java/com/sponus/coreinfrasecurity/config/SecurityConfig.java
Labels: feat, refactor

#309 fix: 배포용 db yml 복구
  core/core-infra-db/src/main/resources/application-db.yml
Labels: fix
