Repository spon-us/SponUs-BE, pull requests merged in 2024-01, with the labels that each got.

#2 ✨ feat : #1 로그인, 회원가입 기능 개발
  .gitignore
  HELP.md
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/sponus/sponusbe/SponusBeApplication.java
  src/main/java/com/sponus/sponusbe/auth/jwt/dto/CachedHttpServletRequest.java
  src/main/java/com/sponus/sponusbe/auth/jwt/dto/JwtPair.java
  src/main/java/com/sponus/sponusbe/auth/jwt/exception/CustomExpiredJwtException.java
  src/main/java/com/sponus/sponusbe/auth/jwt/exception/CustomMalformedException.java
  src/main/java/com/sponus/sponusbe/auth/jwt/exception/CustomNoTokenException.java
  src/main/java/com/sponus/sponusbe/auth/jwt/exception/CustomSignatureException.java
  src/main/java/com/sponus/sponusbe/auth/jwt/exception/status/TokenErrorCode.java
  src/main/java/com/sponus/sponusbe/auth/jwt/filter/CustomLoginFilter.java
  src/main/java/com/sponus/sponusbe/auth/jwt/filter/CustomLogoutHandler.java
  src/main/java/com/sponus/sponusbe/auth/jwt/filter/JwtExceptionFilter.java
  src/main/java/com/sponus/sponusbe/auth/jwt/filter/JwtFilter.java
  src/main/java/com/sponus/sponusbe/auth/jwt/util/JsonUtil.java
  src/main/java/com/sponus/sponusbe/auth/jwt/util/JwtUtil.java
  src/main/java/com/sponus/sponusbe/auth/jwt/util/RedisUtil.java
  src/main/java/com/sponus/sponusbe/auth/jwt/util/ResponseUtil.java
  src/main/java/com/sponus/sponusbe/auth/user/CustomUserDetails.java
  src/main/java/com/sponus/sponusbe/auth/user/CustomUserDetailsService.java
  src/main/java/com/sponus/sponusbe/global/common/ApiResponse.java
  src/main/java/com/sponus/sponusbe/global/common/BaseCode.java
  src/main/java/com/sponus/sponusbe/global/common/BaseEntity.java
  src/main/java/com/sponus/sponusbe/global/common/BaseErrorCode.java
  src/main/java/com/sponus/sponusbe/global/common/exception/ExceptionAdvice.java
  src/main/java/com/sponus/sponusbe/global/common/status/GroupErrorStatus.java
  src/main/java/com/sponus/sponusbe/global/config/CorsConfig.java
  src/main/java/com/sponus/sponusbe/global/config/RedisConfig.java
  src/main/java/com/sponus/sponusbe/global/config/SecurityConfig.java
  src/main/java/com/sponus/sponusbe/global/config/SwaggerConfig.java
  src/main/java/com/sponus/sponusbe/global/dto/ErrorReasonDTO.java
  src/main/java/com/sponus/sponusbe/global/dto/ReasonDTO.java
  src/main/java/com/sponus/sponusbe/group/controller/GroupController.java
  src/main/java/com/sponus/sponusbe/group/dto/GroupJoinRequest.java
  src/main/java/com/sponus/sponusbe/group/dto/GroupJoinResponse.java
  src/main/java/com/sponus/sponusbe/group/entity/Group.java
  src/main/java/com/sponus/sponusbe/group/enums/GroupType.java
  src/main/java/com/sponus/sponusbe/group/enums/SubGroupType.java
  src/main/java/com/sponus/sponusbe/group/repository/GroupJpaRepository.java
  src/main/java/com/sponus/sponusbe/group/repository/GroupRepository.java
  src/main/java/com/sponus/sponusbe/group/repository/GroupRepositoryImpl.java
  src/main/java/com/sponus/sponusbe/group/service/GroupService.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/sponus/sponusbe/SponusBeApplicationTests.java
Labels: feature

#5 💚[CI/CD] Create gradle.yml #3
  .github/workflows/gradle.yml
Labels: ci

#7 ✨ [FEATURE] 기본 엔티티 및 연관관계 설정
  build.gradle
  src/main/java/com/sponus/sponusbe/auth/jwt/exception/status/TokenErrorCode.java
  src/main/java/com/sponus/sponusbe/auth/jwt/filter/JwtExceptionFilter.java
  src/main/java/com/sponus/sponusbe/auth/user/CustomUserDetails.java
  src/main/java/com/sponus/sponusbe/auth/user/CustomUserDetailsService.java
  src/main/java/com/sponus/sponusbe/domain/announcement/entity/Announcement.java
  src/main/java/com/sponus/sponusbe/domain/announcement/entity/AnnouncementAttachment.java
  src/main/java/com/sponus/sponusbe/domain/announcement/entity/AnnouncementImage.java
  src/main/java/com/sponus/sponusbe/domain/announcement/entity/enums/AnnouncementCategory.java
  src/main/java/com/sponus/sponusbe/domain/announcement/entity/enums/AnnouncementStatus.java
  src/main/java/com/sponus/sponusbe/domain/announcement/entity/enums/AnnouncementType.java
  src/main/java/com/sponus/sponusbe/domain/organization/controller/OrganizationController.java
  src/main/java/com/sponus/sponusbe/domain/organization/dto/OrganizationJoinRequest.java
  src/main/java/com/sponus/sponusbe/domain/organization/dto/OrganizationJoinResponse.java
  src/main/java/com/sponus/sponusbe/domain/organization/entity/Organization.java
  src/main/java/com/sponus/sponusbe/domain/organization/entity/OrganizationLink.java
  src/main/java/com/sponus/sponusbe/domain/organization/entity/OrganizationTag.java
  src/main/java/com/sponus/sponusbe/domain/organization/entity/Tag.java
  src/main/java/com/sponus/sponusbe/domain/organization/entity/enums/OrganizationStatus.java
  src/main/java/com/sponus/sponusbe/domain/organization/entity/enums/OrganizationType.java
  src/main/java/com/sponus/sponusbe/domain/organization/entity/enums/SuborganizationType.java
  src/main/java/com/sponus/sponusbe/domain/organization/exception/OrganizationException.java
  src/main/java/com/sponus/sponusbe/domain/organization/repository/OrganizationJpaRepository.java
  src/main/java/com/sponus/sponusbe/domain/organization/repository/OrganizationRepository.java
  src/main/java/com/sponus/sponusbe/domain/organization/repository/OrganizationRepositoryImpl.java
  src/main/java/com/sponus/sponusbe/domain/organization/service/OrganizationService.java
  src/main/java/com/sponus/sponusbe/domain/propose/entity/Propose.java
  src/main/java/com/sponus/sponusbe/domain/propose/entity/ProposeAttachment.java
  src/main/java/com/sponus/sponusbe/domain/propose/entity/ProposeStatus.java
  src/main/java/com/sponus/sponusbe/domain/report/entity/Report.java
  src/main/java/com/sponus/sponusbe/domain/report/entity/ReportAttachment.java
  src/main/java/com/sponus/sponusbe/domain/report/entity/ReportStatus.java
  src/main/java/com/sponus/sponusbe/global/common/ApiResponse.java
  src/main/java/com/sponus/sponusbe/global/common/BaseErrorCode.java
  src/main/java/com/sponus/sponusbe/global/common/code/OrganizationErrorCode.java
  src/main/java/com/sponus/sponusbe/global/common/exception/CustomException.java
  src/main/java/com/sponus/sponusbe/global/common/exception/ExceptionAdvice.java
  src/main/java/com/sponus/sponusbe/global/common/status/GroupErrorStatus.java
  src/main/java/com/sponus/sponusbe/global/config/SecurityConfig.java
  src/main/java/com/sponus/sponusbe/group/controller/GroupController.java
  src/main/java/com/sponus/sponusbe/group/dto/GroupJoinRequest.java
  src/main/java/com/sponus/sponusbe/group/dto/GroupJoinResponse.java
  src/main/java/com/sponus/sponusbe/group/repository/GroupJpaRepository.java
  src/main/java/com/sponus/sponusbe/group/repository/GroupRepository.java
  src/main/java/com/sponus/sponusbe/group/repository/GroupRepositoryImpl.java
  src/main/java/com/sponus/sponusbe/group/service/GroupService.java
Labels: feature

#13 ♻️refactor: BaseCode 인터페이스 제거
  src/main/java/com/sponus/sponusbe/global/common/BaseCode.java
Labels: refactor

#24 💚 [CI/CD] Actions 스크립트 수정
  .github/workflows/gradle.yml
  .gitignore
  Dockerfile
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: ci

#30 📝 [DOCS] 템플릿 수정
  .github/ISSUE_TEMPLATE/♻️-refactor.md
  .github/ISSUE_TEMPLATE/✨-feature.md
  .github/ISSUE_TEMPLATE/🐛-bug.md
  .github/ISSUE_TEMPLATE/👷️-ci.md
  .github/ISSUE_TEMPLATE/📝️-docs.md
  .github/pull_request_template.md
Labels: docs

#32 🐛 [BUG] 시큐리티 문제 수정
  src/main/java/com/sponus/sponusbe/auth/jwt/exception/CustomNoTokenException.java
  src/main/java/com/sponus/sponusbe/auth/jwt/exception/SecurityCustomException.java
  src/main/java/com/sponus/sponusbe/auth/jwt/exception/SecurityErrorCode.java
  src/main/java/com/sponus/sponusbe/auth/jwt/filter/CustomLoginFilter.java
  src/main/java/com/sponus/sponusbe/auth/jwt/filter/CustomLogoutHandler.java
  src/main/java/com/sponus/sponusbe/auth/jwt/filter/JwtExceptionFilter.java
  src/main/java/com/sponus/sponusbe/auth/jwt/filter/JwtFilter.java
  src/main/java/com/sponus/sponusbe/auth/jwt/util/HttpResponseUtil.java
  src/main/java/com/sponus/sponusbe/auth/jwt/util/JsonUtil.java
  src/main/java/com/sponus/sponusbe/auth/jwt/util/JwtUtil.java
  src/main/java/com/sponus/sponusbe/auth/jwt/util/ResponseUtil.java
  src/main/java/com/sponus/sponusbe/global/common/BaseErrorCode.java
  src/main/java/com/sponus/sponusbe/global/common/code/OrganizationErrorCode.java
  src/main/java/com/sponus/sponusbe/global/config/SecurityConfig.java
Labels: bug

#34 ✨ [FEATURE] AWS S3 추가
  build.gradle
  src/main/java/com/sponus/sponusbe/domain/s3/S3Config.java
  src/main/java/com/sponus/sponusbe/domain/s3/S3Controller.java
  src/main/java/com/sponus/sponusbe/domain/s3/S3Service.java
  src/main/java/com/sponus/sponusbe/global/config/SecurityConfig.java
Labels: feature

#35 :sparkles: [FEATURE] 보고서 관련 기능 개발
  .gitignore
  src/main/java/com/sponus/sponusbe/domain/report/Service/ReportQueryService.java
  src/main/java/com/sponus/sponusbe/domain/report/Service/ReportService.java
  src/main/java/com/sponus/sponusbe/domain/report/controller/ReportController.java
  src/main/java/com/sponus/sponusbe/domain/report/dto/AttachmentResponse.java
  src/main/java/com/sponus/sponusbe/domain/report/dto/ReportRequest.java
  src/main/java/com/sponus/sponusbe/domain/report/dto/ReportResponse.java
  src/main/java/com/sponus/sponusbe/domain/report/entity/Report.java
  src/main/java/com/sponus/sponusbe/domain/report/entity/ReportStatus.java
  src/main/java/com/sponus/sponusbe/domain/report/exception/ReportException.java
  src/main/java/com/sponus/sponusbe/domain/report/repository/ReportRepository.java
  src/main/java/com/sponus/sponusbe/global/common/code/ReportErrorCode.java
  src/main/java/com/sponus/sponusbe/global/config/SecurityConfig.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: feature

#37 💚 [CI/CD] S3에 따른 yml 및 배포 스크립트 수정
  .github/workflows/gradle.yml
  src/main/resources/application-prod.yml
Labels: bug, ci

#42 ✨ [FEATURE] 공고 관련 기능 세팅
  src/main/java/com/sponus/sponusbe/domain/announcement/controller/AnnouncementController.java
  src/main/java/com/sponus/sponusbe/domain/announcement/dto/AnnouncementBriefResponse.java
  src/main/java/com/sponus/sponusbe/domain/announcement/dto/AnnouncementCreateRequest.java
  src/main/java/com/sponus/sponusbe/domain/announcement/dto/AnnouncementResponse.java
  src/main/java/com/sponus/sponusbe/domain/announcement/exception/AnnouncementErrorCode.java
  src/main/java/com/sponus/sponusbe/domain/announcement/exception/AnnouncementException.java
  src/main/java/com/sponus/sponusbe/domain/announcement/repository/AnnouncementRepository.java
  src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementQueryService.java
  src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementService.java
Labels: feature

#43 :sparkles: [FEATURE] 공고 작성 기능 개발
  src/main/java/com/sponus/sponusbe/domain/announcement/controller/AnnouncementController.java
  src/main/java/com/sponus/sponusbe/domain/announcement/dto/AnnouncementCreateRequest.java
  src/main/java/com/sponus/sponusbe/domain/announcement/dto/AnnouncementCreateResponse.java
  src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementService.java
Labels: feature

#45 💚 [CI/CD]: ci, cd 파일 분리
  .github/workflows/cd_gradle.yml
  .github/workflows/ci_gradle.yml
  .github/workflows/gradle.yml
Labels: ci

#63 ♻️ refactor: JPQL QueryDSL로 변경
  .github/ISSUE_TEMPLATE/✨-feat.md
  .github/ISSUE_TEMPLATE/🐛-fix.md
  .gitignore
  build.gradle
  http/test.http
  src/main/generated/com/sponus/sponusbe/domain/announcement/entity/QAnnouncement.java
  src/main/generated/com/sponus/sponusbe/domain/announcement/entity/QAnnouncementAttachment.java
  src/main/generated/com/sponus/sponusbe/domain/announcement/entity/QAnnouncementImage.java
  src/main/generated/com/sponus/sponusbe/domain/organization/entity/QOrganization.java
  src/main/generated/com/sponus/sponusbe/domain/organization/entity/QOrganizationLink.java
  src/main/generated/com/sponus/sponusbe/domain/organization/entity/QOrganizationTag.java
  src/main/generated/com/sponus/sponusbe/domain/organization/entity/QTag.java
  src/main/generated/com/sponus/sponusbe/domain/propose/entity/QPropose.java
  src/main/generated/com/sponus/sponusbe/domain/propose/entity/QProposeAttachment.java
  src/main/generated/com/sponus/sponusbe/domain/report/entity/QReport.java
  src/main/generated/com/sponus/sponusbe/domain/report/entity/QReportAttachment.java
  src/main/generated/com/sponus/sponusbe/global/common/QBaseEntity.java
  src/main/java/com/sponus/sponusbe/domain/propose/controller/ProposeController.java
  src/main/java/com/sponus/sponusbe/domain/propose/repository/ProposeCustomRepository.java
  src/main/java/com/sponus/sponusbe/domain/propose/repository/ProposeCustomRepositoryImpl.java
  src/main/java/com/sponus/sponusbe/domain/propose/repository/ProposeRepository.java
  src/main/java/com/sponus/sponusbe/domain/propose/service/ProposeQueryService.java
  src/main/java/com/sponus/sponusbe/domain/s3/S3Config.java
  src/main/java/com/sponus/sponusbe/domain/s3/S3Service.java
Labels: refactor

#68 📝 docs: 이슈 템플릿 복구
  .github/ISSUE_TEMPLATE/✨-feat.md
  .github/ISSUE_TEMPLATE/🐛-fix.md
Labels: docs

#65 ✨ feat: 조직 조회 기능 개발
  http/test.http
  src/main/java/com/sponus/sponusbe/domain/organization/controller/OrganizationController.java
  src/main/java/com/sponus/sponusbe/domain/organization/service/OrganizationQueryService.java
Labels: feat

#73 ️♻️ refactor: 시큐리티 구조 개선
  src/main/java/com/sponus/sponusbe/auth/jwt/exception/CustomExpiredJwtException.java
  src/main/java/com/sponus/sponusbe/auth/jwt/exception/CustomMalformedException.java
  src/main/java/com/sponus/sponusbe/auth/jwt/exception/CustomNoTokenException.java
  src/main/java/com/sponus/sponusbe/auth/jwt/exception/CustomSignatureException.java
  src/main/java/com/sponus/sponusbe/auth/jwt/exception/JwtAccessDeniedHandler.java
  src/main/java/com/sponus/sponusbe/auth/jwt/exception/JwtAuthenticationEntryPoint.java
  src/main/java/com/sponus/sponusbe/auth/jwt/exception/SecurityCustomException.java
  src/main/java/com/sponus/sponusbe/auth/jwt/exception/SecurityErrorCode.java
  src/main/java/com/sponus/sponusbe/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/sponus/sponusbe/auth/jwt/filter/JwtExceptionFilter.java
  src/main/java/com/sponus/sponusbe/auth/jwt/util/JwtUtil.java
  src/main/java/com/sponus/sponusbe/global/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sponus/sponusbe/global/config/SecurityConfig.java
Labels: refactor

#80 🐛 fix: generated 폴더 및 하위 파일 제거
  src/main/generated/com/sponus/sponusbe/domain/announcement/entity/QAnnouncement.java
  src/main/generated/com/sponus/sponusbe/domain/announcement/entity/QAnnouncementAttachment.java
  src/main/generated/com/sponus/sponusbe/domain/announcement/entity/QAnnouncementImage.java
  src/main/generated/com/sponus/sponusbe/domain/organization/entity/QOrganization.java
  src/main/generated/com/sponus/sponusbe/domain/organization/entity/QOrganizationLink.java
  src/main/generated/com/sponus/sponusbe/domain/organization/entity/QOrganizationTag.java
  src/main/generated/com/sponus/sponusbe/domain/organization/entity/QTag.java
  src/main/generated/com/sponus/sponusbe/domain/propose/entity/QPropose.java
  src/main/generated/com/sponus/sponusbe/domain/propose/entity/QProposeAttachment.java
  src/main/generated/com/sponus/sponusbe/domain/report/entity/QReport.java
  src/main/generated/com/sponus/sponusbe/domain/report/entity/QReportAttachment.java
  src/main/generated/com/sponus/sponusbe/global/common/QBaseEntity.java
Labels: fix

#82 🐛 fix: 엔티티 수정(Announcement, Propose)
  src/main/java/com/sponus/sponusbe/domain/announcement/entity/Announcement.java
  src/main/java/com/sponus/sponusbe/domain/propose/entity/Propose.java
  src/main/java/com/sponus/sponusbe/domain/propose/entity/ProposeImage.java
Labels: fix
